"""Document IR models."""

from lewlm.documents.ir.models import (
    CalloutBlock,
    Citation,
    DocumentIR,
    DocumentOutputFormat,
    DocumentSection,
    HeaderFooterContent,
    ImageBlock,
    ListBlock,
    ParagraphBlock,
    StyleToken,
    TableBlock,
)
from lewlm.documents.ir.style import (
    EMPHASIS_VALUES,
    MAX_FONT_SIZE_PT,
    MIN_FONT_SIZE_PT,
    DocumentStyleSheet,
    ResolvedStyle,
    StyleElement,
    StyleRoleSpec,
    StyleTokenRole,
    StyleValueKind,
    normalize_style_value,
    resolve_style_role,
    style_role_specs,
)

__all__ = [
    "EMPHASIS_VALUES",
    "MAX_FONT_SIZE_PT",
    "MIN_FONT_SIZE_PT",
    "CalloutBlock",
    "Citation",
    "DocumentIR",
    "DocumentOutputFormat",
    "DocumentSection",
    "DocumentStyleSheet",
    "HeaderFooterContent",
    "ImageBlock",
    "ListBlock",
    "ParagraphBlock",
    "ResolvedStyle",
    "StyleElement",
    "StyleRoleSpec",
    "StyleToken",
    "StyleTokenRole",
    "StyleValueKind",
    "TableBlock",
    "normalize_style_value",
    "resolve_style_role",
    "style_role_specs",
]
