from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from urllib import error, request


def _post_json(base_url: str, path: str, payload: dict[str, object]) -> dict[str, object]:
    raw = json.dumps(payload).encode("utf-8")
    req = request.Request(
        f"{base_url.rstrip('/')}{path}",
        data=raw,
        headers={"content-type": "application/json", "accept": "application/json"},
        method="POST",
    )
    try:
        with request.urlopen(req) as response:
            return json.loads(response.read().decode("utf-8"))
    except error.HTTPError as exc:  # pragma: no cover - example script
        body = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"{exc.code} {exc.reason}: {body}") from exc


def _iter_sse(base_url: str, path: str):
    req = request.Request(
        f"{base_url.rstrip('/')}{path}",
        headers={"accept": "text/event-stream"},
        method="GET",
    )
    try:
        with request.urlopen(req) as response:
            event_name: str | None = None
            data_lines: list[str] = []
            for raw_line in response:
                line = raw_line.decode("utf-8").rstrip("\r\n")
                if not line:
                    if data_lines:
                        payload = "\n".join(data_lines)
                        yield event_name, payload
                    event_name = None
                    data_lines = []
                    continue
                if line.startswith(":"):
                    continue
                if line.startswith("event:"):
                    event_name = line.partition(":")[2].strip()
                    continue
                if line.startswith("data:"):
                    data_lines.append(line.partition(":")[2].lstrip())
    except error.HTTPError as exc:  # pragma: no cover - example script
        body = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"{exc.code} {exc.reason}: {body}") from exc


def _demo_document() -> dict[str, object]:
    return {
        "title": "LewLM HTTP integration example",
        "metadata": {"source": "examples/http_api_integration.py"},
        "sections": [
            {
                "heading": "Summary",
                "blocks": [
                    {
                        "type": "paragraph",
                        "text": "This document was generated by a host application calling LewLM over HTTP.",
                    }
                ],
            }
        ],
    }


def _demo_citation_context() -> dict[str, object]:
    return {
        "sources": [
            {
                "source_id": "src-demo",
                "path": "/tmp/integration-example.md",
                "source_type": "markdown",
                "source_name": "integration-example.md",
                "source_label": "LewLM Integration Example",
                "media_type": "text/markdown",
                "metadata": {},
            }
        ],
        "chunks": [
            {
                "chunk_id": "src-demo-sec-0001-chunk-0001",
                "text": "LewLM is a local-first backend package that host applications can embed or call over HTTP.",
                "source_id": "src-demo",
                "section_id": "src-demo-sec-0001",
                "source_label": "LewLM Integration Example",
                "section_label": "LewLM Integration Example / Summary",
                "section_heading": "Summary",
                "section_level": 1,
                "source_name": "integration-example.md",
                "source_path": "/tmp/integration-example.md",
                "source_type": "markdown",
                "metadata": {"chunk_index": 0},
            }
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Minimal LewLM HTTP integration example.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8080", help="LewLM server base URL.")
    subparsers = parser.add_subparsers(dest="surface", required=True)

    subparsers.add_parser("chat", help="Call /v1/chat/completions")
    subparsers.add_parser("chat-structured", help="Call /v1/chat/completions with an output schema")
    subparsers.add_parser("chat-grounded", help="Call /v1/chat/completions with citation_context")
    subparsers.add_parser("responses", help="Call /v1/responses")
    subparsers.add_parser("responses-structured", help="Call /v1/responses with a response_format contract")
    subparsers.add_parser("responses-grounded", help="Call /v1/responses with citation_context")
    subparsers.add_parser("embeddings", help="Call /v1/embeddings")
    subparsers.add_parser("retrieval", help="Call /v1/retrieval/context")
    subparsers.add_parser("rerank", help="Call /v1/rerank")

    ingest_parser = subparsers.add_parser("document-ingest", help="Call /v1/documents/ingest")
    ingest_parser.add_argument("paths", nargs="+", help="Local file paths LewLM is allowed to ingest.")

    subparsers.add_parser("document-generate", help="Call /v1/documents/generate")

    events_parser = subparsers.add_parser("events", help="Read a few events from /v1/events")
    events_parser.add_argument("--count", type=int, default=3, help="Number of SSE events to print before exiting.")

    args = parser.parse_args()
    base_url = args.base_url

    if args.surface == "chat":
        payload = {
            "messages": [
                {"role": "user", "content": "Summarize LewLM for a host application in one sentence."},
            ],
            "stream": False,
        }
        print(json.dumps(_post_json(base_url, "/v1/chat/completions", payload), indent=2))
        return

    if args.surface == "chat-structured":
        payload = {
            "messages": [
                {"role": "user", "content": "Return a JSON summary of LewLM for a host application."},
            ],
            "response_format": {
                "type": "json_schema",
                "name": "summary_contract",
                "schema": {
                    "type": "object",
                    "properties": {
                        "summary": {"type": "string"},
                    },
                    "required": ["summary"],
                    "additionalProperties": False,
                },
            },
            "include_prompt_trace": True,
            "stream": False,
        }
        print(json.dumps(_post_json(base_url, "/v1/chat/completions", payload), indent=2))
        return

    if args.surface == "chat-grounded":
        payload = {
            "messages": [
                {"role": "user", "content": "Summarize LewLM in one sentence and ground it in the supplied context."},
            ],
            "citation_context": _demo_citation_context(),
            "stream": False,
        }
        print(json.dumps(_post_json(base_url, "/v1/chat/completions", payload), indent=2))
        return

    if args.surface == "responses":
        payload = {
            "input": [
                {"role": "user", "content": "Summarize LewLM for a host application in one sentence."},
            ],
            "stream": False,
        }
        print(json.dumps(_post_json(base_url, "/v1/responses", payload), indent=2))
        return

    if args.surface == "responses-structured":
        payload = {
            "input": "Return a JSON summary of LewLM for a host application.",
            "response_format": {
                "type": "json_schema",
                "name": "summary_contract",
                "schema": {
                    "type": "object",
                    "properties": {
                        "summary": {"type": "string"},
                    },
                    "required": ["summary"],
                    "additionalProperties": False,
                },
            },
            "include_prompt_trace": True,
            "stream": False,
        }
        print(json.dumps(_post_json(base_url, "/v1/responses", payload), indent=2))
        return

    if args.surface == "responses-grounded":
        payload = {
            "input": "Summarize LewLM in one sentence and ground it in the supplied context.",
            "citation_context": _demo_citation_context(),
            "stream": False,
        }
        print(json.dumps(_post_json(base_url, "/v1/responses", payload), indent=2))
        return

    if args.surface == "embeddings":
        payload = {
            "input": [
                "LewLM local backend package",
                "Stable request and response examples",
            ]
        }
        print(json.dumps(_post_json(base_url, "/v1/embeddings", payload), indent=2))
        return

    if args.surface == "rerank":
        payload = {
            "query": "integration bundle for host apps",
            "documents": [
                "LewLM publishes JSON schemas and examples for main HTTP surfaces.",
                "This note is about a weather application.",
                "LewLM streams runtime events over SSE and WebSocket.",
            ],
            "top_n": 2,
        }
        print(json.dumps(_post_json(base_url, "/v1/rerank", payload), indent=2))
        return

    if args.surface == "retrieval":
        payload = {
            "query": "typed helper for host applications",
            "candidate_sources": [
                {
                    "source_id": "source-1",
                    "path": "/tmp/app-notes.md",
                    "source_type": "markdown",
                    "source_name": "app-notes.md",
                    "source_label": "app-notes.md",
                }
            ],
            "candidate_chunks": [
                {
                    "chunk_id": "chunk-1",
                    "text": "LewLM exposes typed helper methods for host applications.",
                    "source_id": "source-1",
                    "section_id": "section-1",
                    "source_label": "app-notes.md",
                    "section_label": "app-notes.md / Section 1",
                },
                {
                    "chunk_id": "chunk-2",
                    "text": "This unrelated note is about weather forecasts.",
                    "source_id": "source-1",
                    "section_id": "section-2",
                    "source_label": "app-notes.md",
                    "section_label": "app-notes.md / Section 2",
                },
            ],
            "top_k": 1,
        }
        print(json.dumps(_post_json(base_url, "/v1/retrieval/context", payload), indent=2))
        return

    if args.surface == "document-ingest":
        payload = {"paths": [str(Path(path).expanduser().resolve()) for path in args.paths]}
        print(json.dumps(_post_json(base_url, "/v1/documents/ingest", payload), indent=2))
        return

    if args.surface == "document-generate":
        payload = {
            "output_format": "markdown",
            "file_name": "integration-example.md",
            "document": _demo_document(),
        }
        print(json.dumps(_post_json(base_url, "/v1/documents/generate", payload), indent=2))
        return

    if args.surface == "events":
        seen = 0
        for event_name, payload in _iter_sse(base_url, "/v1/events"):
            print(event_name or "message")
            print(payload)
            print()
            seen += 1
            if seen >= args.count:
                return
        return

    raise SystemExit(f"Unsupported surface: {args.surface}")


if __name__ == "__main__":
    sys.exit(main())
