#!/usr/bin/env python3
"""Export image-flavor dependency inputs from ``pyproject.toml``.

The container images install dependencies *before* the application source is
copied, so an app-only edit never re-resolves or recompiles them. For that to
work the dependency layer needs a small, stable input file that changes only
when the dependency set changes. This script derives those files from
``pyproject.toml`` so the project file stays the single source of truth:

    requirements/bridge.txt   base package only (LewLM in front of Ollama or
                              another loopback server)
    requirements/serving.txt  base + ``llamacpp_runtime`` (GGUF inference)
    requirements/full.txt     base + ``llamacpp`` + ``documents`` (serving,
                              HF->GGUF conversion, documents/OCR)

These are unpinned *inputs*; pinned, hashed locks resolved on the target
platform belong in ``requirements/locks/`` (see
``scripts/docker/lock_dependencies.sh``) and are selected with the
``DEPENDENCY_INPUT`` build argument.

Usage:
    python scripts/export_dependency_inputs.py            # rewrite the files
    python scripts/export_dependency_inputs.py --check    # exit 1 when stale
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
REQUIREMENTS_DIR = REPO_ROOT / "requirements"

#: Image flavor -> extras layered on top of the base dependencies. Order is the
#: documented lean-to-full order; every later flavor is a superset of the one
#: before it, and the contract test enforces that.
IMAGE_FLAVORS: dict[str, tuple[str, ...]] = {
    "bridge": (),
    "serving": ("llamacpp_runtime",),
    "full": ("llamacpp", "documents"),
}

_HEADER = (
    "# Generated by scripts/export_dependency_inputs.py from pyproject.toml.\n"
    "# Do not edit by hand; rerun the script after changing dependencies.\n"
    "# Flavor: {flavor} (extras: {extras})\n"
)


def load_project() -> dict[str, object]:
    data = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))
    project = data.get("project")
    if not isinstance(project, dict):
        raise SystemExit("pyproject.toml has no [project] table")
    return project


def flavor_requirements(flavor: str, project: dict[str, object] | None = None) -> list[str]:
    """Return the sorted, de-duplicated requirement strings for one flavor."""

    if flavor not in IMAGE_FLAVORS:
        raise KeyError(f"unknown image flavor {flavor!r}; expected one of {', '.join(IMAGE_FLAVORS)}")
    resolved = project if project is not None else load_project()
    base = resolved.get("dependencies", [])
    optional = resolved.get("optional-dependencies", {})
    if not isinstance(base, list) or not isinstance(optional, dict):
        raise SystemExit("pyproject.toml dependency tables have an unexpected shape")

    requirements: set[str] = {str(item) for item in base}
    for extra in IMAGE_FLAVORS[flavor]:
        group = optional.get(extra)
        if not isinstance(group, list):
            raise SystemExit(f"pyproject.toml is missing the {extra!r} extra needed by flavor {flavor!r}")
        requirements.update(str(item) for item in group)
    return sorted(requirements, key=str.casefold)


def render(flavor: str, project: dict[str, object] | None = None) -> str:
    extras = ", ".join(IMAGE_FLAVORS[flavor]) or "none"
    body = "\n".join(flavor_requirements(flavor, project))
    return _HEADER.format(flavor=flavor, extras=extras) + body + "\n"


def output_path(flavor: str) -> Path:
    return REQUIREMENTS_DIR / f"{flavor}.txt"


def export(*, check: bool) -> int:
    project = load_project()
    stale: list[str] = []
    for flavor in IMAGE_FLAVORS:
        expected = render(flavor, project)
        path = output_path(flavor)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if check:
            stale.append(str(path.relative_to(REPO_ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    if stale:
        print(
            "dependency inputs are stale; run `python scripts/export_dependency_inputs.py`: " + ", ".join(stale),
            file=sys.stderr,
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Fail instead of rewriting when a file is stale.")
    args = parser.parse_args(argv)
    return export(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
